### ISSUE TITLE
Two Different Codechef Solution File

### ISSUE THREAD

**Issue by Yash1256** [Yash1256/CompetitiveCodingSolutions#43]
There are two different Codechef Solution Folder, make that into one Folder i.e Make only one folder for codechef Solution.

**Comment by lostgirljourney** [comment]
Alright, I'm moving my files from Codechef to Codechef solutions; is it fine @Yash1256 ?

**Comment by Yash1256** [comment]
Yes @lostgirljourney

**Comment by Yash1256** [comment]
@lostgirljourney in Codechef README.md is not there so also make README.md for those 3 questions also.

**Comment by lostgirljourney** [comment]
Assign me this issue if you can @Yash1256!
