### ISSUE TITLE
Make a README.md file for Hackerank

### ISSUE THREAD

**Issue by Yash1256** [Yash1256/CompetitiveCodingSolutions#45]
As Hackerrank Folder dosen't have the README.md file make a separate README.md file for the Hackerrank folder which contains the Questions of above solved Problems.

**Comment by zahinekbal** [comment]
@Yash1256 Can I Contribute on this issues 
I will add hackerRank problem in readme file will add Implementation in another file...
Please assign it to me..

**Comment by Yash1256** [comment]
@zahinekbal You just have to follow the problem and find it's Question URL and simply made a README.md for that as
[Question Name](Question URL).
> will add Implementation in another file...
No Need for This Step.
I am assigning this Issue to you.
If have any doubt feel free to ask.

**Comment by zahinekbal** [comment]
@Yash1256  I added Readme.md for all problems of hackerrank..
please check my code and review my PR..
