### ISSUE TITLE
Add Solutions For LeetCode Monthly Contests

### ISSUE THREAD

**Issue by Yash1256** [Yash1256/CompetitiveCodingSolutions#55]
As There are monthly Practice Contest going on LeetCode So make a new Folder for LeetCode in which there will be Day wised Solution Available for a Month.

**Comment by EmberCS15** [comment]
Hi @Yash1256 , I can work on this and make the required folders, but I have a few follow up questions - 

* Will this folder contain solutions to BiWeekly / Weekly contests or Solutions to the Daily challenge contest (Like October Challenge) ?
* Am I to simply add the directory structure or add solutions to the questions as well ?
* Does this directory structure sound good - 

```
leetcode|
        | WeeklyContests
        | BiWeeklyContests
        | Monthly Challenges|
                            | 2020 |
                                   | October
```

**Comment by Yash1256** [comment]
Well done @EmberCS15  I do agree with your Idea but I think mostly people solve monthly LeetCode Contest instead of weekly and biweekly thereby they will be created but questions will be very less in those folders or may be empty that's why I asked for Monthly wise I you can add good amount of questions for weekly and biweekly I would surely welcome your thoughts. You can work on this PR I assign this to u.
All the best.👍

**Comment by EmberCS15** [comment]
Thank you for the clarification. I will raise a PR for this.

**Comment by EmberCS15** [comment]
@Yash1256 Can you add `hacktoberfest` label to the issue ?
