### ISSUE TITLE
Ordering of Algorithm Folder

### ISSUE THREAD

**Issue by Yash1256** [Yash1256/CompetitiveCodingSolutions#61]
As in the Algorithm Folder most of the Algorithms are there in a scattered manner, so make a PR in which there will be folder's named `graph`,`DP`,`Sorting`,`Searching` etc and all the algorithms will be arranged in their Respective Folder.

**Comment by icecreamcake101** [comment]
can i grab this

**Comment by Yash1256** [comment]
@icecreamcake101 Why not...

**Comment by NancyAgrawal** [comment]
Hey, is someone still working on it?

**Comment by Yash1256** [comment]
Nope @NancyAgrawal You Can Take This Issue. If any Doubt feel free to ask.

**Comment by NancyAgrawal** [comment]
There are some general algorithms that don't fit in any of the `graph`, `DP`, `Sorting`, `Searching`. Should I put them in `Others` folder or leave them there itself in the `algorithms` folder?

These are the referred algorithms:
1.  [advance_algo](https://github.com/Yash1256/CompetitiveCodingSolutions/blob/master/Algorithms/advance_algo.go): consists of the greedy implementation of the knapsack, returning possible combinations, etc.
2.  [longest-increasing-subsequent.py](https://github.com/Yash1256/CompetitiveCodingSolutions/blob/master/Algorithms/longest-increasing-subsequent.py) 
3.  [password.py](https://github.com/Yash1256/CompetitiveCodingSolutions/blob/master/Algorithms/password.py)
4. [quad_algo.cpp](https://github.com/Yash1256/CompetitiveCodingSolutions/blob/master/Algorithms/quad_algo.cpp) : checks if a quadrilateral is a parallelogram.
5. [traversals_in_tree.c](https://github.com/Yash1256/CompetitiveCodingSolutions/blob/master/Algorithms/traversals_in_tree.c)

**Comment by Yash1256** [comment]
@NancyAgrawal You May Put Them in Another Folder
