### ISSUE TITLE
Codechef Solutions

### ISSUE THREAD

**Issue by lostgirljourney** [Yash1256/CompetitiveCodingSolutions#9]
@Yash1256, can I contribute for codechef problem solutions?

**Comment by Yash1256** [comment]
Yup @lostgirljourney You can

**Comment by lostgirljourney** [comment]
Okay thank you! @Yash1256

**Comment by Yash1256** [comment]
@lostgirljourney any Updates for Questions ? Or Should I close this Issue?

**Comment by lostgirljourney** [comment]
You can close this issue, I will add questions or you can open this for all by assigning me. :)
